html_dict = {
    "name": ".col-name .tooltip .bp3-text-overflow-ellipsis",
    "age": ".list .col-ae",
    "overall_rating": ".list .col-oa",
    "height": ".list .col-hi",
    "weight": ".list .col-wi",
    "potential": ".list .col-pt",
    "preferred_foot": ".list .col-pf",
    "best_overall": ".list .col-bo",
    "best_postion": ".list .col-bp",
    "market_value": ".list .col-vl",
    "attacking": ".list .col-ta",
    "team": ".bp3-text-overflow-ellipsis a",
    "contract_duration": ".sub",
    "joined": ".list .col-jt",
    "id": ".list .col-pi",
    "gk_diving": ".list .col-gd",
    "gk_handling": ".list .col-gh",
    "gk_kicking": ".list .col-gc",
    "gk_positioning": ".list .col-gp",
    "gk_reflexes": ".list .col-gr",
    "week_foot": ".list .col-wk",
    "skill_moves": ".list .col-sk",
    "pace": ".list .col-pac",
    "shooting": ".list .col-sho",
    "passing": ".list .col-pas",
    "dribbling" : ".list .col-dri",
    "defending": ".list .col-def",
    "physics": ".list .col-phy",
    "total_small_stats": ".list .col-tt"
}